### ISSUE TITLE
<a href="https://stackblitz.com/~/github.com/vitejs/vite/pull/15653"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Run & review this pull request in [StackBlitz Codeflow](https://stackblitz.com/~/github.com/vitejs/vite/pull/15653)._

### ISSUE THREAD

**Issue by juli64** [vitejs/vite-plugin-react-pages#169]
<a href="https://stackblitz.com/~/github.com/vitejs/vite/pull/15653"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Run & review this pull request in [StackBlitz Codeflow](https://stackblitz.com/~/github.com/vitejs/vite/pull/15653)._

_Originally posted by @stackblitz[bot] in https://github.com/vitejs/vite/issues/15653#issuecomment-1900231306_
            
```[tasklist]
### Tasks
- [ ] https://github.com/vitejs/vite-plugin-react-pages/issues/167
```

```[tasklist]
### Tasks
- [ ] https://github.com/vitejs/vite-plugin-react-pages/pull/165
- [ ] https://github.com/vitejs/vite-plugin-react-pages/issues/149
- [ ] https://github.com/vitejs/vite-plugin-react-pages/pull/164
- [ ] https://github.com/vitejs/vite-plugin-react-pages/pull/162
```

**Comment by csr632** [comment]
If you mean the ci error, it is fixed now.
